language: node_js
node_js:
- '10'
- '12'
script:
- npm run test:ci
- npm run build
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
after_success:
- "./.ci/update-gh-pages.sh > /dev/null 2>&1"
cache: false
env:
  global:
  - secure: i4TbUi5aVY1HusytrmJMxbAVnyaSbnpTI4pArEfk2t3xkODVeuToxd9kwn5y2R08fROmxqK2MY2nnabnHdLiyit1/uMjuZHLPyRRf2oqgut0pIE+kDonM8tQsQuuIn3FvlD99dFQK4qcRPJu/IxEe3MgRS67hwWGsyFXN81QwG0TsncR1oQBC3Hj8W57DmX1qNzwunNUbYWdwvwuMiBOJmw058xP43bUlWcmtSRw1USaFvqz+ETy9dI/1lVxKh4iMiw87d1ybzxnfOvwN7tkMA/s1rUsUi09hBCmnFVY5PTw8OAkfAtlkGpOcK8rjcK0FrFs/KjGqdwBxbJIxJuSc6PSIhe0UTj2kfRw7J3NiguEQFma7Z9wb3QCquApHLRqfKDRh36Yx4MslBWmo/VxD+CvG0NHxIGEVG3AgqS+loEu+jiS8EE7L02BZ/qyKkgVsp8G7dXvzlPgtOkeDjp5UHTLrBB+HjKBqtWlYMzg/UNYlDFmuZtJCcjKLxRFMsYwnwEmqSqOzMIHu7baUf8AVKbJBrCcNObPxhYtbx7bYqy75h1POPe6b7ejyTRw27g24aKN8yQK1hlpn9BVl8s5eMjEV+Q3NUdTxspkCm3wB41M3F/yrjBeFil2+659g0Occh9mwnewudwjGSmH8HGlO1R6xkxUfADrG61rNr/jVgg=
